### ISSUE TITLE
Неверная информация при прикреплении кошелька

### ISSUE THREAD

**Issue by vasinkd** [vasinkd/WMSCrypto#4]
При прикреплении кошелька видим информацию "Ниже Вы увидите фразу для восстановления кошелька. Рекомендуем записать ее и хранить в надежном месте! В случае потери эта фраза не может быть восстановлена!", но на самом деле ниже - QR-ключ и это сбивает с толку. Надо заменить эту фразу на "После нажатия кнопки "Создать кошелек" Вы увидите QR-ключ, необходимый для проведения операций с кошельком, полученным из фразы для восстановления. Обязательно сохраните его".

**Comment by totaki** [comment]
Проверяй
